#include <iostream>
#include <vector>
#include <unordered_map>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include <winsock2.h>
#include <ws2tcpip.h>
#include <cassert>


#pragma comment(lib, "ws2_32.lib")

const size_t k_max_msg = 32 << 20;

struct Conn {
    SOCKET fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    std::vector<uint8_t> incoming;  // data to be parsed by the application
    std::vector<uint8_t> outgoing;  // responses generated by the application
};

static void die(const char* msg) {
    int err = WSAGetLastError();
    std::cout << err << " " << msg << std::endl;
    abort();
}

// append to the back
static void
buf_append(std::vector<uint8_t>& buf, const uint8_t* data, size_t len) {
    buf.insert(buf.end(), data, data + len);
}
// remove from the front
static void buf_consume(std::vector<uint8_t>& buf, size_t n) {
    buf.erase(buf.begin(), buf.begin() + n);
}

static bool try_one_request(Conn* conn) {
    // 3. Try to parse the accumulated buffer.
    // Protocol: message header
    if (conn->incoming.size() < 4) {
        return false;   // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    len = ntohl(len);
    if (len > k_max_msg) {  // protocol error
        conn->want_close = true;
        return false;   // want close
    }
    // Protocol: message body
    if (4 + len > conn->incoming.size()) {
        return false;   // want read
    }
    const uint8_t* request = &conn->incoming[4];
    // 4. Process the parsed message.
    
    std::string msg = std::string((char*)request, len);

    std::cout << "len:" << len << std::endl << msg << std::endl;
    uint32_t res_len_net = htonl(len);
    // generate the response (echo)
    buf_append(conn->outgoing, (const uint8_t*)&res_len_net, 4);
    buf_append(conn->outgoing, request, len);
    // 5. Remove the message from `Conn::incoming`.
    buf_consume(conn->incoming, 4 + len);
    return true;
}

static void fd_set_nb(SOCKET fd) {
    u_long mode = 1;      // 1 = non-blocking
    ioctlsocket(fd, FIONBIO, &mode);
}

static Conn* handle_accept(SOCKET fd) {
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    SOCKET connfd = accept(fd, (struct sockaddr*)&client_addr, &addrlen);
    if (connfd < 0) {
        return NULL;
    }
    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);
    // create a `struct Conn`
    Conn* conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true; // read the 1st request
    return conn;
}

static void handle_read(Conn* conn) {
    // 1. Do a non-blocking read.
    uint8_t buf[64 * 1024];

    int rv = recv(conn->fd, (char*)buf, sizeof(buf), 0);

    if (rv <= 0) {
        if (rv == 0) {
            // Connection closed gracefully (EOF)
        }
        else {
            int err = WSAGetLastError();

            if (err == WSAEWOULDBLOCK) {
                // Non-blocking socket: no data available
                return;
            }

            // Real error
        }

        conn->want_close = true;
        return;
    }
    // 2. Add new data to the `Conn::incoming` buffer.
    buf_append(conn->incoming, buf, (size_t)rv);
    // 3. Try to parse the accumulated buffer.
    // 4. Process the parsed message.
    // 5. Remove the message from `Conn::incoming`.
    while (try_one_request(conn));

    // update the readiness intention
    if (conn->outgoing.size() > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;

        return handle_write(conn);
    }
}

static void handle_write(Conn* conn) {
    assert(conn->outgoing.size() > 0);
    int rv = send(conn->fd, (char*)conn->outgoing.data(), conn->outgoing.size(),0);

    if (rv == SOCKET_ERROR) {
        int err = WSAGetLastError();

        if (err == WSAEWOULDBLOCK) {
            // Non-blocking: cannot send now
        }
        else {
            conn->want_close = true;    // error handling
            return;
        }
    }

    // remove written data from `outgoing`
    buf_consume(conn->outgoing, (size_t)rv);

    if (conn->outgoing.size() == 0) {   // all data written
        conn->want_read = true;
        conn->want_write = false;
    }
}

int main() {
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
        die("WSAStartup()");
    }

    SOCKET fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (fd == INVALID_SOCKET) {
        die("socket()");
    }

    // SO_REUSEADDR
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (const char*)&val, sizeof(val));

    // bind
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(fd, (struct sockaddr*)&addr, sizeof(addr)) == SOCKET_ERROR) {
        die("bind()");
    }

    // listen
    if (listen(fd, SOMAXCONN) == SOCKET_ERROR) {
        die("listen()");
    }


    // a map of all client connections, keyed by fd
    std::unordered_map<SOCKET, Conn*> fd2conn;

    // the event loop
    std::vector<struct pollfd> poll_args;
    while (true)
    {
        // prepare the arguments of the poll()
        poll_args.clear();
        // put the listening sockets in the first position
        struct pollfd pfd = { fd, POLLIN, 0 };
        poll_args.push_back(pfd);
        // the rest are connection sockets
        for (auto [st, conn] : fd2conn) {
            if (!conn) {
                continue;
            }
            struct pollfd pfd = { conn->fd, 0, 0 };
            // poll() flags from the application's intent
            if (conn->want_read) {
                pfd.events |= POLLIN;
            }
            if (conn->want_write) {
                pfd.events |= POLLOUT;
            }
            poll_args.push_back(pfd);
        }

        // wait for readiness
        int rv = WSAPoll(poll_args.data(), (ULONG)poll_args.size(), -1);
        if (rv < 0 && errno == EINTR)continue;
        if (rv < 0) die("poll");

        // handle the listening socket
        if (poll_args[0].revents) {
            if (Conn* conn = handle_accept(fd)) {
                // put it into the map
                fd2conn[conn->fd] = conn;
            }
        }

        // handle connection sockets
        for (size_t i = 1; i < poll_args.size(); ++i) { // note: skip the 1st
            uint32_t ready = poll_args[i].revents;
            Conn* conn = fd2conn[poll_args[i].fd];
            if (ready & POLLIN) {
                handle_read(conn);  // application logic
            }
            if (ready & POLLOUT) {
                handle_write(conn); // application logic
            }

            // close the socket from socket error or application logic
            if ((ready & POLLERR) || conn->want_close) {
                (void)closesocket(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }

    WSACleanup();
    return 0;
}
