#include <iostream>
#include <vector>
#include <unordered_map>
#include <map>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include <winsock2.h>
#include <ws2tcpip.h>
#include <cassert>
#include "hashtable.h"

#pragma comment(lib, "ws2_32.lib")

#define container_of(ptr, T, member) \
    ((T *)( (char *)ptr - offsetof(T, member) ))

const size_t k_max_msg = 32 << 20;
const size_t k_max_args = 200 * 1000;

static struct {
    HashTable ht;              // the object
    HashTable::HMap db;        // the map
} g_data;

struct Entry {
    HashTable::HNode node;  // hashtable node
    std::string key;
    std::string val;
};

struct Conn {
    SOCKET fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    std::vector<uint8_t> incoming;  // data to be parsed by the application
    std::vector<uint8_t> outgoing;  // responses generated by the application
};

enum {
    RES_OK = 0,
    RES_ERR = 1,    // error
    RES_NX = 2,     // key not found
};

struct Response {
    uint32_t status = 0;
    std::vector<uint8_t> data;
};

static void die(const char* msg) {
    int err = WSAGetLastError();
    std::cout << err << " " << msg << std::endl;
    abort();
}

// append to the back
static void buf_append(std::vector<uint8_t>& buf, const uint8_t* data, size_t len) {
    buf.insert(buf.end(), data, data + len);
}

// remove from the front
static void buf_consume(std::vector<uint8_t>& buf, size_t n) {
    buf.erase(buf.begin(), buf.begin() + n);
}

static bool read_u32(const uint8_t*& cur, const uint8_t* end, uint32_t& out) {
    if (cur + 4 > end) {
        return false;
    }
    memcpy(&out, cur, 4);
    out = ntohl(out);
    cur += 4;
    return true;
}

static bool read_str(const uint8_t*& cur, const uint8_t* end, size_t n, std::string& out) {
    if (cur + n > end) {
        return false;
    }
    out.assign(cur, cur + n);
    cur += n;
    return true;
}

static int32_t parse_req(const uint8_t* data, size_t size, std::vector<std::string>& out) {
    /*
        data looks like that
        
        |nstr|len|str1|len|str2|...|len|strn|

        nstr -> know the number of messages
    */
    const uint8_t* end = data + size;
    uint32_t nstr = 0;
    if (!read_u32(data, end, nstr)) {
        return -1;
    }
    if (nstr > k_max_args) {
        return -1;  // safety limit
    }

    while (out.size() < nstr) {
        uint32_t len = 0;
        if (!read_u32(data, end, len)) {
            return -1;
        }
        out.push_back(std::string());
        if (!read_str(data, end, len, out.back())) {
            return -1;
        }
    }
    if (data != end) {
        return -1;  // trailing garbage
    }
    return 0;
}

// equality comparison for `struct Entry`
static bool entry_eq(HashTable::HNode* lhs, HashTable::HNode* rhs) {
    struct Entry* le = container_of(lhs, struct Entry, node);
    struct Entry* re = container_of(rhs, struct Entry, node);
    return le->key == re->key;
}

// FNV hash
static uint64_t str_hash(const uint8_t* data, size_t len) {
    uint32_t h = 0x811C9DC5;
    for (size_t i = 0; i < len; i++) {
        h = (h + data[i]) * 0x01000193;
    }
    return h;
}

static void do_get(std::vector<std::string>& cmd, Response& out) {
    // a dummy `Entry` just for the lookup
    Entry key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t*)key.key.data(), key.key.size());
    // hashtable lookup
    HashTable::HNode* node = g_data.ht.hm_lookup(&g_data.db, &key.node, entry_eq);
    if (!node) {
        out.status = RES_NX;
        return;
    }
    // copy the value
    const std::string& val = container_of(node, Entry, node)->val;
    assert(val.size() <= k_max_msg);
    out.data.assign(val.begin(), val.end());
}

static void do_set(std::vector<std::string>& cmd, Response&) {
    // a dummy `Entry` just for the lookup
    Entry key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t*)key.key.data(), key.key.size());
    // hashtable lookup
    HashTable::HNode* node = g_data.ht.hm_lookup(&g_data.db, &key.node, entry_eq);

    if (node) {
        container_of(node, Entry, node)->val.swap(cmd[2]);
    }
    else {
        Entry* ent = new Entry();
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        ent->val.swap(cmd[2]);

        g_data.ht.hm_insert(&g_data.db, &ent->node);
    }
}

static void do_del(std::vector<std::string>& cmd, Response&) {
    // a dummy `Entry` just for the lookup
    Entry key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t*)key.key.data(), key.key.size());
    // hashtable delete
    HashTable::HNode* node = g_data.ht.hm_delete(&g_data.db, &key.node, entry_eq);

    if (node) {
        delete container_of(node, Entry, node);
    }
}

static void do_request(std::vector<std::string>& cmd, Response& out) {
    if (cmd.size() == 2 && cmd[0] == "get") {
        return do_get(cmd, out);
    }
    else if (cmd.size() == 3 && cmd[0] == "set") {
        return do_set(cmd, out);
    }
    else if (cmd.size() == 2 && cmd[0] == "del") {
        return do_del(cmd, out);
    }
    else {
        out.status = RES_ERR;       // unrecognized command
    }
}

static void make_response(const Response& resp, std::vector<uint8_t>& out) {
    uint32_t resp_len = 4 + (uint32_t)resp.data.size();
    resp_len = htonl(resp_len);
    uint32_t status = htonl(resp.status);
    buf_append(out, (const uint8_t*)&resp_len, 4);
    buf_append(out, (const uint8_t*)&status, 4);
    buf_append(out, resp.data.data(), resp.data.size());
}

static bool try_one_request(Conn* conn) {
    // 3. Try to parse the accumulated buffer.
    // Protocol: message header
    if (conn->incoming.size() < 4) {
        return false;   // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    len = ntohl(len);
    if (len > k_max_msg) {  // protocol error
        conn->want_close = true;
        return false;   // want close
    }
    // Protocol: message body
    if (4 + len > conn->incoming.size()) {
        return false;   // want read
    }
    const uint8_t* request = &conn->incoming[4];
    // 4. Process the parsed message.
    
    std::string msg = std::string((char*)request, len);

    //std::cout << msg << std::endl;

    std::vector<std::string> cmd;
    if (parse_req(request, len, cmd) < 0) {
        conn->want_close = true;
        return false;   // error
    }
    Response resp;
    do_request(cmd, resp);
    make_response(resp, conn->outgoing);

    // 5. Remove the message from `Conn::incoming`.
    buf_consume(conn->incoming, 4 + len);
    return true;
}

static void fd_set_nb(SOCKET fd) {
    u_long mode = 1;      // 1 = non-blocking
    ioctlsocket(fd, FIONBIO, &mode);
}

static Conn* handle_accept(SOCKET fd) {
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    SOCKET connfd = accept(fd, (struct sockaddr*)&client_addr, &addrlen);
    if (connfd < 0) {
        return NULL;
    }
    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);
    // create a `struct Conn`
    Conn* conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true; // read the 1st request
    return conn;
}

static void handle_write(Conn* conn) {
    assert(conn->outgoing.size() > 0);
    int rv = send(conn->fd, (char*)conn->outgoing.data(), conn->outgoing.size(), 0);

    if (rv == SOCKET_ERROR) {
        int err = WSAGetLastError();

        if (err == WSAEWOULDBLOCK) {
            // Non-blocking: cannot send now
            return;
        }
        else {
            conn->want_close = true;    // error handling
            return;
        }
    }

    if (rv == 0)return;

    // remove written data from `outgoing`
    buf_consume(conn->outgoing, (size_t)rv);

    if (conn->outgoing.size() == 0) {   // all data written
        conn->want_read = true;
        conn->want_write = false;
    }
}

static void handle_read(Conn* conn) {
    // 1. Do a non-blocking read.
    uint8_t buf[64 * 1024];

    int rv = recv(conn->fd, (char*)buf, sizeof(buf), 0);

    if (rv <= 0) {
        if (rv == 0) {
            // Connection closed gracefully (EOF)
        }
        else {
            int err = WSAGetLastError();

            if (err == WSAEWOULDBLOCK) {
                // Non-blocking socket: no data available
                return;
            }

            // Real error
        }

        conn->want_close = true;
        return;
    }
    // 2. Add new data to the `Conn::incoming` buffer.
    buf_append(conn->incoming, buf, (size_t)rv);
    // 3. Try to parse the accumulated buffer.
    // 4. Process the parsed message.
    // 5. Remove the message from `Conn::incoming`.
    while (try_one_request(conn));

    // update the readiness intention
    if (conn->outgoing.size() > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;

        handle_write(conn);
    }
}

int main() {
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
        die("WSAStartup()");
    }

    SOCKET fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (fd == INVALID_SOCKET) {
        die("socket()");
    }

    // SO_REUSEADDR
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (const char*)&val, sizeof(val));

    // bind
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(fd, (struct sockaddr*)&addr, sizeof(addr)) == SOCKET_ERROR) {
        die("bind()");
    }

    // listen
    if (listen(fd, SOMAXCONN) == SOCKET_ERROR) {
        die("listen()");
    }

    // a map of all client connections, keyed by fd
    std::unordered_map<SOCKET, Conn*> fd2conn;

    // the event loop
    std::vector<struct pollfd> poll_args;
    while (true)
    {
        // prepare the arguments of the poll()
        poll_args.clear();
        // put the listening sockets in the first position
        struct pollfd pfd = { fd, POLLIN, 0 };
        poll_args.push_back(pfd);
        // the rest are connection sockets
        for (auto [st, conn] : fd2conn) {
            if (!conn) {
                continue;
            }
            struct pollfd pfd = { conn->fd, 0, 0 };
            // poll() flags from the application's intent
            if (conn->want_read) {
                pfd.events |= POLLIN;
            }
            if (conn->want_write) {
                pfd.events |= POLLOUT;
            }
            poll_args.push_back(pfd);
        }

        // wait for readiness
        int rv = WSAPoll(poll_args.data(), (ULONG)poll_args.size(), -1);
        if (rv == SOCKET_ERROR) {
            int err = WSAGetLastError();
        }
        if (rv < 0) die("poll");

        // handle the listening socket
        if (poll_args[0].revents) {
            if (Conn* conn = handle_accept(fd)) {
                // put it into the map
                fd2conn[conn->fd] = conn;
            }
        }

        // handle connection sockets
        for (size_t i = 1; i < poll_args.size(); ++i) { // note: skip the 1st
            uint32_t ready = poll_args[i].revents;
            Conn* conn = fd2conn[poll_args[i].fd];
            if (ready & POLLIN) {
                handle_read(conn);  // application logic
            }
            if (ready & POLLOUT) {
                handle_write(conn); // application logic
            }

            // close the socket from socket error or application logic
            if ((ready & POLLERR) || conn->want_close) {
                (void)closesocket(conn->fd);
                fd2conn.erase(conn->fd);
                delete conn;
            }
        }
    }

    WSACleanup();
    return 0;
}
