#include <iostream>
#include <vector>
#include <unordered_map>
#include <map>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

#include <winsock2.h>
#include <ws2tcpip.h>
#include <cassert>
#include "common.h"
#include "hashtable.h"
#include "zset.h"

#pragma comment(lib, "ws2_32.lib")

typedef std::vector<uint8_t> Buffer;

const size_t k_max_msg = 32 << 20;
const size_t k_max_args = 200 * 1000;

 struct {
    HashTable ht;              // the object
    HashTable::HMap db;        // the map
} g_data;

 struct Entry {
     HashTable::HNode node;
     std::string key;

     uint32_t type;

     std::string str;
     ZSet zset;
 };

struct Conn {
    SOCKET fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    Buffer incoming;  // data to be parsed by the application
    Buffer outgoing;  // responses generated by the application
};

enum {
    ERR_UNKNOWN = 1,    // unknown command
    ERR_TOO_BIG = 2,    // response too big
    ERR_BAD_TYP = 3,    // unexpected value type
    ERR_BAD_ARG = 4,    // bad arguments
};

enum {
    TAG_NIL = 0,    // nil
    TAG_ERR = 1,    // error code + msg
    TAG_STR = 2,    // string
    TAG_INT = 3,    // int64
    TAG_DBL = 4,    // double
    TAG_ARR = 5,    // array
};

enum {
    T_INIT = 0,
    T_STR = 1,
    T_ZSET = 2,
};

 void die(const char* msg) {
    int err = WSAGetLastError();
    std::cout << err << " " << msg << std::endl;
    abort();
}

 static Entry* entry_new(uint32_t type) {
     Entry* ent = new Entry();
     ent->type = type;
     return ent;
 }

 static void entry_del(Entry* ent) {
     if (ent->type == T_ZSET) {
         ZSet::zset_clear(&ent->zset);
     }
     delete ent;
 }

// append to the back
void buf_append(Buffer& buf, const uint8_t* data, size_t len) {
    buf.insert(buf.end(), data, data + len);
}

void buf_append_u8(Buffer& buf, uint8_t data) {
    buf.push_back(data);
}

void buf_append_u32(Buffer& buf, uint32_t data) {
    uint32_t net = htonl(data);
    buf_append(buf, (const uint8_t*)&net, 4);
}

void buf_append_i64(Buffer& buf, int64_t data) {
    buf_append(buf, (const uint8_t*)&data, 8);
}

void buf_append_dbl(Buffer& buf, double data) {
    buf_append(buf, (const uint8_t*)&data, 8);
}

// remove from the front
void buf_consume(Buffer& buf, size_t n) {
    buf.erase(buf.begin(), buf.begin() + n);
}

bool read_u32(const uint8_t*& cur, const uint8_t* end, uint32_t& out) {
    if (cur + 4 > end) {
        return false;
    }
    memcpy(&out, cur, 4);
    out = ntohl(out);
    cur += 4;
    return true;
}

bool read_str(const uint8_t*& cur, const uint8_t* end, size_t n, std::string& out) {
    if (cur + n > end) {
        return false;
    }
    out.assign(cur, cur + n);
    cur += n;
    return true;
}

 int32_t parse_req(const uint8_t* data, size_t size, std::vector<std::string>& out) {
    /*
        data looks like that
        
        |nstr|len|str1|len|str2|...|len|strn|

        nstr -> know the number of messages
    */
    const uint8_t* end = data + size;
    uint32_t nstr = 0;
    if (!read_u32(data, end, nstr)) {
        return -1;
    }
    if (nstr > k_max_args) {
        return -1;  // safety limit
    }

    while (out.size() < nstr) {
        uint32_t len = 0;
        if (!read_u32(data, end, len)) {
            return -1;
        }
        out.push_back(std::string());
        if (!read_str(data, end, len, out.back())) {
            return -1;
        }
    }
    if (data != end) {
        return -1;  // trailing garbage
    }
    return 0;
}

// equality comparison for `struct Entry`
 struct LookupKey {
     HashTable::HNode node;
     std::string key;
 };

 bool entry_eq(HashTable::HNode* node, HashTable::HNode* key) {
     Entry* ent = container_of(node, Entry, node);
     LookupKey* keydata = container_of(key, LookupKey, node);
     return ent->key == keydata->key;
 }

 void out_nil(Buffer& out) {
    buf_append_u8(out, TAG_NIL);
}

 void out_str(Buffer& out, const char* s, size_t size) {
    buf_append_u8(out, TAG_STR);
    buf_append_u32(out, (uint32_t)size);
    buf_append(out, (const uint8_t*)s, size);
}

void out_int(Buffer& out, int64_t val) {
    buf_append_u8(out, TAG_INT);
    buf_append_i64(out, val);
}

static void out_dbl(Buffer& out, double val) {
    buf_append_u8(out, TAG_DBL);
    buf_append_dbl(out, val);
}

void out_arr(Buffer& out, uint32_t n) {
    buf_append_u8(out, TAG_ARR);
    buf_append_u32(out, n);
}

void out_err(Buffer& out, uint32_t code, const std::string& msg) {
    buf_append_u8(out, TAG_ERR);
    buf_append_u32(out, code);
    buf_append_u32(out, (uint32_t)msg.size());
    buf_append(out, (const uint8_t*)msg.data(), msg.size());
}

void do_get(std::vector<std::string>& cmd, Buffer& out) {
    // a dummy `Entry` just for the lookup
    Entry key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t*)key.key.data(), key.key.size());
    // hashtable lookup
    HashTable::HNode* node = g_data.ht.hm_lookup(&g_data.db, &key.node, entry_eq);
    if (!node) {
        return out_nil(out);
    }
    // copy the value
    Entry* ent = container_of(node, Entry, node);
    if (ent->type != T_STR) {
        return out_err(out, ERR_BAD_TYP, "not a string value");
    }
    return out_str(out, ent->str.data(), ent->str.size());
}

static void do_set(std::vector<std::string>& cmd, Buffer& out) {
    // a dummy struct just for the lookup
    LookupKey key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t*)key.key.data(), key.key.size());
    // hashtable lookup
    HashTable::HNode* node = HashTable::hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (node) {
        // found, update the value
        Entry* ent = container_of(node, Entry, node);
        if (ent->type != T_STR) {
            return out_err(out, ERR_BAD_TYP, "a non-string value exists");
        }
        ent->str.swap(cmd[2]);
    }
    else {
        // not found, allocate & insert a new pair
        Entry* ent = entry_new(T_STR);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        ent->str.swap(cmd[2]);
        HashTable::hm_insert(&g_data.db, &ent->node);
    }
    return out_nil(out);
}

void do_del(std::vector<std::string>& cmd, Buffer& out) {
    // a dummy `Entry` just for the lookup
    Entry key;
    key.key.swap(cmd[1]);
    key.node.hcode = str_hash((uint8_t*)key.key.data(), key.key.size());
    // hashtable delete
    HashTable::HNode* node = g_data.ht.hm_delete(&g_data.db, &key.node, entry_eq);

    if (node) {
        entry_del(container_of(node, Entry, node));
    }
    return out_int(out, node ? 1 : 0);
}

 bool cb_keys(HashTable::HNode* node, void* arg) {
    Buffer& out = *(Buffer*)arg;
    const std::string& key = container_of(node, Entry, node)->key;
    out_str(out, key.data(), key.size());
    return true;
}

 void do_keys(std::vector<std::string>&, Buffer& out) {
    out_arr(out, (uint32_t)g_data.ht.hm_size(&g_data.db));
    g_data.ht.hm_foreach(&g_data.db, &cb_keys, (void*)&out);
}

 void response_begin(Buffer& out, size_t* header) {
    *header = out.size();       // messege header position
    buf_append_u32(out, 0);     // reserve space
}

 size_t response_size(Buffer& out, size_t header) {
    return out.size() - header - 4;
}

 void response_end(Buffer& out, size_t header) {
    size_t msg_size = response_size(out, header);
    if (msg_size > k_max_msg) {
        out.resize(header + 4);
        out_err(out, ERR_TOO_BIG, "response is too big.");
        msg_size = response_size(out, header);
    }
    // message header
    uint32_t len = htonl((uint32_t)msg_size);
    memcpy(&out[header], &len, 4);
}

 static bool str2dbl(const std::string& s, double& out) {
     char* endp = NULL;
     out = strtod(s.c_str(), &endp);
     return endp == s.c_str() + s.size() && !isnan(out);
 }

 static bool str2int(const std::string& s, int64_t& out) {
     char* endp = NULL;
     out = strtoll(s.c_str(), &endp, 10);
     return endp == s.c_str() + s.size();
 }

 // zadd zset score name
 static void do_zadd(std::vector<std::string>& cmd, Buffer& out) {
     double score = 0;
     if (!str2dbl(cmd[2], score)) {
         return out_err(out, ERR_BAD_ARG, "expect float");
     }

     // look up or create the zset
     LookupKey key;
     key.key.swap(cmd[1]);
     key.node.hcode = str_hash((uint8_t*)key.key.data(), key.key.size());
     HashTable::HNode* hnode = g_data.ht.hm_lookup(&g_data.db, &key.node, &entry_eq);

     Entry* ent = NULL;
     if (!hnode) {   // insert a new key
         ent = entry_new(T_ZSET);
         ent->key.swap(key.key);
         ent->node.hcode = key.node.hcode;
         g_data.ht.hm_insert(&g_data.db, &ent->node);
     }
     else {        // check the existing key
         ent = container_of(hnode, Entry, node);
         if (ent->type != T_ZSET) {
             return out_err(out, ERR_BAD_TYP, "expect zset");
         }
     }

     // add or update the tuple
     const std::string& name = cmd[3];
     bool added = ZSet::zset_insert(&ent->zset, name.data(), name.size(), score);
     return out_int(out, (int64_t)added);
 }

 static ZSet k_empty_zset;

 static ZSet* expect_zset(std::string& s) {
     LookupKey key;
     key.key.swap(s);
     key.node.hcode = str_hash((uint8_t*)key.key.data(), key.key.size());
     HashTable::HNode* hnode = g_data.ht.hm_lookup(&g_data.db, &key.node, &entry_eq);
     if (!hnode) {   // a non-existent key is treated as an empty zset
         return (ZSet*)&k_empty_zset;
     }
     Entry* ent = container_of(hnode, Entry, node);
     return ent->type == T_ZSET ? &ent->zset : NULL;
 }

 // zrem zset name
 static void do_zrem(std::vector<std::string>& cmd, Buffer& out) {
     ZSet* zset = expect_zset(cmd[1]);
     if (!zset) {
         return out_err(out, ERR_BAD_TYP, "expect zset");
     }

     const std::string& name = cmd[2];
     ZSet::ZNode* znode = ZSet::zset_lookup(zset, name.data(), name.size());
     if (znode) {
         ZSet::zset_delete(zset, znode);
     }
     return out_int(out, znode ? 1 : 0);
 }

 // zscore zset name
 static void do_zscore(std::vector<std::string>& cmd, Buffer& out) {
     ZSet* zset = expect_zset(cmd[1]);
     if (!zset) {
         return out_err(out, ERR_BAD_TYP, "expect zset");
     }

     const std::string& name = cmd[2];
     ZSet::ZNode* znode = ZSet::zset_lookup(zset, name.data(), name.size());
     return znode ? out_dbl(out, znode->score) : out_nil(out);
 }

 static size_t out_begin_arr(Buffer& out) {
     out.push_back(TAG_ARR);
     buf_append_u32(out, 0);     // filled by out_end_arr()
     return out.size() - 4;      // the `ctx` arg
 }

 static void out_end_arr(Buffer& out, size_t ctx, uint32_t n) {
     assert(out[ctx - 1] == TAG_ARR);
     uint32_t net_n = htonl(n);
     memcpy(&out[ctx], &net_n, 4);
 }

 // zquery zset score name offset limit
 static void do_zquery(std::vector<std::string>& cmd, Buffer& out) {
     // parse args
     double score = 0;
     if (!str2dbl(cmd[2], score)) {
         return out_err(out, ERR_BAD_ARG, "expect fp number");
     }
     const std::string& name = cmd[3];
     int64_t offset = 0, limit = 0;
     if (!str2int(cmd[4], offset) || !str2int(cmd[5], limit)) {
         return out_err(out, ERR_BAD_ARG, "expect int");
     }

     // get the zset
     ZSet* zset = expect_zset(cmd[1]);
     if (!zset) {
         return out_arr(out,0);
     }

     // seek to the key
     if (limit <= 0) {
         return out_arr(out, 0);
     }
     ZSet::ZNode* znode = ZSet::zset_seekge(zset, score, name.data(), name.size());
     znode = ZSet::znode_offset(znode, offset);

     // output
     size_t ctx = out_begin_arr(out);
     int64_t n = 0;
     while (znode && n < limit) {
         out_str(out, znode->name, znode->len);
         out_dbl(out, znode->score);
         znode = ZSet::znode_offset(znode, +1);
         n++;
     }
     out_end_arr(out, ctx, (uint32_t)n*2);
 }

 static void do_request(std::vector<std::string>& cmd, Buffer& out) {
     if (cmd.size() == 2 && cmd[0] == "get") {
         return do_get(cmd, out);
     }
     else if (cmd.size() == 3 && cmd[0] == "set") {
         return do_set(cmd, out);
     }
     else if (cmd.size() == 2 && cmd[0] == "del") {
         return do_del(cmd, out);
     }
     else if (cmd.size() == 1 && cmd[0] == "keys") {
         return do_keys(cmd, out);
     }
     else if (cmd.size() == 4 && cmd[0] == "zadd") {
         return do_zadd(cmd, out);
     }
     else if (cmd.size() == 3 && cmd[0] == "zrem") {
         return do_zrem(cmd, out);
     }
     else if (cmd.size() == 3 && cmd[0] == "zscore") {
         return do_zscore(cmd, out);
     }
     else if (cmd.size() == 6 && cmd[0] == "zquery") {
         return do_zquery(cmd, out);
     }
     else {
         return out_err(out, ERR_UNKNOWN, "unknown command.");
     }
 }

 bool try_one_request(Conn* conn) {
    // 3. Try to parse the accumulated buffer.
    // Protocol: message header
    if (conn->incoming.size() < 4) {
        return false;   // want read
    }
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    len = ntohl(len);
    if (len > k_max_msg) {  // protocol error
        conn->want_close = true;
        return false;   // want close
    }
    // Protocol: message body
    if (4 + len > conn->incoming.size()) {
        return false;   // want read
    }
    const uint8_t* request = &conn->incoming[4];
    // 4. Process the parsed message.
    
    //std::string msg = std::string((char*)request, len);

    //std::cout << msg << std::endl;

    std::vector<std::string> cmd;
    if (parse_req(request, len, cmd) < 0) {
        conn->want_close = true;
        return false;   // error
    }

    size_t header_pos = 0;
    response_begin(conn->outgoing, &header_pos);
    do_request(cmd, conn->outgoing);
    response_end(conn->outgoing, header_pos);

    // 5. Remove the message from `Conn::incoming`.
    buf_consume(conn->incoming, 4 + len);
    return true;
}

 void fd_set_nb(SOCKET fd) {
    u_long mode = 1;      // 1 = non-blocking
    ioctlsocket(fd, FIONBIO, &mode);
}

 Conn* handle_accept(SOCKET fd) {
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    SOCKET connfd = accept(fd, (struct sockaddr*)&client_addr, &addrlen);
    if (connfd < 0) {
        return NULL;
    }
    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);
    // create a `struct Conn`
    Conn* conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true; // read the 1st request
    return conn;
}

 void handle_write(Conn* conn) {
    assert(conn->outgoing.size() > 0);
    int rv = send(conn->fd, (char*)conn->outgoing.data(), conn->outgoing.size(), 0);

    if (rv == SOCKET_ERROR) {
        int err = WSAGetLastError();

        if (err == WSAEWOULDBLOCK) {
            // Non-blocking: cannot send now
            return;
        }
        else {
            conn->want_close = true;    // error handling
            return;
        }
    }

    if (rv == 0)return;

    // remove written data from `outgoing`
    buf_consume(conn->outgoing, (size_t)rv);

    if (conn->outgoing.size() == 0) {   // all data written
        conn->want_read = true;
        conn->want_write = false;
    }
}

 void handle_read(Conn* conn) {
    // 1. Do a non-blocking read.
    uint8_t buf[64 * 1024];

    int rv = recv(conn->fd, (char*)buf, sizeof(buf), 0);

    if (rv <= 0) {
        if (rv == 0) {
            // Connection closed gracefully (EOF)
        }
        else {
            int err = WSAGetLastError();

            if (err == WSAEWOULDBLOCK) {
                // Non-blocking socket: no data available
                return;
            }

            // Real error
        }

        conn->want_close = true;
        return;
    }
    // 2. Add new data to the `Conn::incoming` buffer.
    buf_append(conn->incoming, buf, (size_t)rv);
    // 3. Try to parse the accumulated buffer.
    // 4. Process the parsed message.
    // 5. Remove the message from `Conn::incoming`.
    while (try_one_request(conn));

    // update the readiness intention
    if (conn->outgoing.size() > 0) {    // has a response
        conn->want_read = false;
        conn->want_write = true;

        handle_write(conn);
    }
}

int main() {
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
        die("WSAStartup()");
    }

    SOCKET fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (fd == INVALID_SOCKET) {
        die("socket()");
    }

    // SO_REUSEADDR
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (const char*)&val, sizeof(val));

    // bind
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(fd, (struct sockaddr*)&addr, sizeof(addr)) == SOCKET_ERROR) {
        die("bind()");
    }

    // listen
    if (listen(fd, SOMAXCONN) == SOCKET_ERROR) {
        die("listen()");
    }

    // a map of all client connections, keyed by fd
    std::unordered_map<SOCKET, Conn*> fd2conn;

    // the event loop
    std::vector<struct pollfd> poll_args;
    while (true)
    {
        // prepare the arguments of the poll()
        poll_args.clear();
        // put the listening sockets in the first position
        struct pollfd pfd = { fd, POLLIN, 0 };
        poll_args.push_back(pfd);
        // the rest are connection sockets
        for (auto [st, conn] : fd2conn) {
            if (!conn) {
                continue;
            }
            struct pollfd pfd = { conn->fd, 0, 0 };
            // poll() flags from the application's intent
            if (conn->want_read) {
                pfd.events |= POLLIN;
            }
            if (conn->want_write) {
                pfd.events |= POLLOUT;
            }
            poll_args.push_back(pfd);
        }

        // wait for readiness
        int rv = WSAPoll(poll_args.data(), (ULONG)poll_args.size(), -1);
        if (rv == SOCKET_ERROR) {
            int err = WSAGetLastError();
        }
        if (rv < 0) die("poll");

        // handle the listening socket
        if (poll_args[0].revents) {
            if (Conn* conn = handle_accept(fd)) {
                // put it into the map
                fd2conn[conn->fd] = conn;
            }
        }

        // handle connection sockets
        for (size_t i = 1; i < poll_args.size(); ++i) { // note: skip the 1st
            uint32_t ready = poll_args[i].revents;
            Conn* conn = fd2conn[poll_args[i].fd];
            if (ready & POLLIN) {
                handle_read(conn);  // application logic
            }
            if (ready & POLLOUT) {
                handle_write(conn); // application logic
            }

            // close the socket from socket error or application logic
            if ((ready & POLLERR) || conn->want_close) {
                (void)closesocket(conn->fd);
                fd2conn.erase(conn->fd);
                delete conn;
            }
        }
    }

    WSACleanup();
    return 0;
}
